import fs from 'fs';
import path from 'path';
import dynamic from 'next/dynamic';
import { LeadCard } from './components/LeadCard';



interface Lead {
  name: string;
  category: string;
  address: string;
  city: string;
  zipCode: string;
  phone?: string;
  email?: string;
  website?: string;
  zone?: string;
  lat?: number;
  lng?: number;
}

async function getLeads(): Promise<Lead[]> {
  // In a real app, this would be a DB call
  // For now, read from the JSON file generated by the scraper
  const filePath = path.join(process.cwd(), 'data', 'leads.json');
  try {
    if (!fs.existsSync(filePath)) {
      return [];
    }
    const fileContents = fs.readFileSync(filePath, 'utf8');
    return JSON.parse(fileContents);
  } catch (e) {
    console.error("Failed to read leads", e);
    return [];
  }
}

export default async function Home() {
  const leads = await getLeads();

  return (
    <main className="flex h-screen w-full flex-col bg-slate-950 font-sans text-slate-50">
      {/* Navbar */}
      <header className="flex h-16 shrink-0 items-center justify-between border-b border-indigo-500/10 bg-slate-900/50 px-6 backdrop-blur-md">
        <div className="flex items-center gap-2">
          <div className="h-8 w-8 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-600" />
          <h1 className="text-xl font-bold tracking-tight text-white">Montaigu Leads</h1>
        </div>
        <div className="flex items-center gap-4">
          <span className="text-sm text-slate-400">{leads.length} companies found</span>
          <button className="rounded-lg bg-indigo-600 px-4 py-2 text-sm font-semibold text-white transition-hover hover:bg-indigo-500">
            Export CSV
          </button>
        </div>
      </header>

      {/* Content */}
      <div className="flex flex-1 overflow-hidden bg-slate-950">
        <div className="flex h-full w-full flex-col">
          {/* Filters */}
          <div className="sticky top-0 z-10 border-b border-indigo-500/10 bg-slate-900/80 p-4 backdrop-blur-md">
            <div className="mx-auto max-w-7xl">
              <input
                type="text"
                placeholder="Search companies..."
                className="w-full max-w-md rounded-xl border border-white/10 bg-white/5 px-4 py-2 text-sm text-white placeholder-slate-500 focus:border-indigo-500 focus:outline-none focus:ring-1 focus:ring-indigo-500"
              />
            </div>
          </div>

          {/* Scrollable List */}
          <div className="flex-1 overflow-y-auto p-4 scrollbar-thin scrollbar-track-transparent scrollbar-thumb-white/10">
            <div className="mx-auto grid max-w-7xl gap-4 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4">
              {leads.map((lead, idx) => (
                <LeadCard key={idx} lead={lead} />
              ))}
            </div>
            {leads.length === 0 && (
              <div className="mt-20 text-center text-slate-500">
                No leads found. Run the scraper first.
              </div>
            )}
          </div>
        </div>
      </div>
    </main>
  );
}
